# Site settings
title: The Estate
email: booljayj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/The-Estate" # the subpath of your site, e.g. /blog/
url: "http://booljayj.github.io/The-Estate" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  booljayj

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true

# Default Front Matter
# eventually phase most of this out and put info in files themselves
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Collections
collections: null